default_args = {
    "domain": "adroit",
    "actor_lr": 3e-5,
    "critic_lr": 3e-4,
    "hidden_dims": [256, 256, 256],
    "gamma": 0.99,
    "tau": 0.005,
    "alpha": 0.1,
    "auto_alpha": True,
    "target_entropy": None,
    "alpha_lr": 3e-5,
    "deterministic_backup": True,
    "max_q_backup": True,
    "norm_reward": True,
    "num_q_ensemble": 10,

    "dynamics_lr": 3e-4,
    "dynamics_max_epochs": None,
    "max_epochs_since_update": 10,
    "dynamics_hidden_dims": [512, 512, 256, 256],
    "dynamics_weight_decay": [2.5e-5, 5e-5, 7.5e-5, 7.5e-5, 1e-4],
    "n_ensemble": 7,
    "n_elites": 5,
    "rollout_freq": 1000,
    "rollout_batch_size": 50000,
    "rollout_length": 1,
    "penalty-coef": 1.0,
    "num_samples": 10,
    "model_retain_epochs": 5,
    "real_ratio": 0.05,
    "load_dynamics_path": None,

    "epoch": 200,
    "step_per_epoch": 1000,
    "eval_episodes": 10,
    "batch_size": 256,
    "lr_scheduler": False,
}